language: node_js

node_js:
  - "10"
  - "12"

before_install:
  # As now, travis provides a version of yarn that is too for Delisp
  # as it does not support the workspaces functionality.
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn global add codecov

script:
  - yarn lint
  - yarn build
  - yarn test --coverage
  - codecov
